services:
  - type: web
    name: floorplan2d-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -c gunicorn_config.py app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
